/* ZERIX 2.0 browser visual layer. */
import './main.css';

type Settings={panelName:string;logoUrl:string;primary:string;secondary:string;accent:string;radius:string;glow:number;compact:boolean;customCss:string};
const KEY='zerix-theme-settings-v2';
const defaults:Settings={panelName:'ZERIX',logoUrl:'',primary:'#8b5cf6',secondary:'#22d3ee',accent:'#3b82f6',radius:'16px',glow:.22,compact:false,customCss:''};
const get=():Settings=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}};
function rootStyle(s:Settings){const r=document.documentElement;r.style.setProperty('--zerix-primary',s.primary);r.style.setProperty('--zerix-secondary',s.secondary);r.style.setProperty('--zerix-accent',s.accent);r.style.setProperty('--zerix-radius',s.radius);r.style.setProperty('--zerix-glow',String(s.glow));document.body?.classList.toggle('zerix-compact',s.compact);document.title=`${s.panelName} • Pterodactyl`;let st=document.getElementById('zerix-custom-css') as HTMLStyleElement|null;if(!st){st=document.createElement('style');st.id='zerix-custom-css';document.head.appendChild(st)}st.textContent=s.customCss||''}
function icon(){let l=document.querySelector<HTMLLinkElement>('link[data-zerix-icon]');if(!l){l=document.createElement('link');l.rel='icon';l.type='image/svg+xml';l.dataset.zerixIcon='true';document.head.appendChild(l)}l.href='/assets/zerix-icon.svg'}
function logo(url:string){if(!url)return;document.querySelectorAll<HTMLImageElement>('img').forEach(i=>{const a=(i.alt||'').toLowerCase();if(a.includes('logo')||i.dataset.zerixLogo)i.src=url})}
function admin(){const u=(window as any).PterodactylUser;return !!(u?.rootAdmin||u?.root_admin)}
function editor(){if(!admin()||document.getElementById('zerix-theme-panel'))return;const b=document.createElement('button');b.id='zerix-theme-open';b.type='button';b.textContent='✦ ZERIX';const p=document.createElement('section');p.id='zerix-theme-panel';p.hidden=true;p.innerHTML=`<h3>ZERIX 2.0</h3><p>Customize your ZERIX visual layer.</p><label>Panel name</label><input id="zx-name" maxlength="40"><label>Logo URL</label><input id="zx-logo" type="url" placeholder="https://..."><div class="zerix-row"><div><label>Primary</label><input id="zx-primary" type="color"></div><div><label>Secondary</label><input id="zx-secondary" type="color"></div></div><label>Accent</label><input id="zx-accent" type="color"><label>Radius</label><input id="zx-radius" placeholder="16px"><label>Glow 0–1</label><input id="zx-glow" type="number" min="0" max="1" step=".01"><label class="zerix-check"><input id="zx-compact" type="checkbox"> Compact mode</label><label>Custom CSS</label><textarea id="zx-css" placeholder="Optional custom CSS"></textarea><div class="zerix-actions"><button id="zerix-save" type="button">Save</button><button id="zerix-reset" type="button">Reset</button></div>`;document.body.append(b,p);const fill=()=>{const s=get();(p.querySelector('#zx-name')as HTMLInputElement).value=s.panelName;(p.querySelector('#zx-logo')as HTMLInputElement).value=s.logoUrl;(p.querySelector('#zx-primary')as HTMLInputElement).value=s.primary;(p.querySelector('#zx-secondary')as HTMLInputElement).value=s.secondary;(p.querySelector('#zx-accent')as HTMLInputElement).value=s.accent;(p.querySelector('#zx-radius')as HTMLInputElement).value=s.radius;(p.querySelector('#zx-glow')as HTMLInputElement).value=String(s.glow);(p.querySelector('#zx-compact')as HTMLInputElement).checked=s.compact;(p.querySelector('#zx-css')as HTMLTextAreaElement).value=s.customCss};b.onclick=()=>{p.hidden=!p.hidden;fill()};p.querySelector('#zerix-save')?.addEventListener('click',()=>{const s:Settings={panelName:(p.querySelector('#zx-name')as HTMLInputElement).value.trim()||'ZERIX',logoUrl:(p.querySelector('#zx-logo')as HTMLInputElement).value.trim(),primary:(p.querySelector('#zx-primary')as HTMLInputElement).value,secondary:(p.querySelector('#zx-secondary')as HTMLInputElement).value,accent:(p.querySelector('#zx-accent')as HTMLInputElement).value,radius:(p.querySelector('#zx-radius')as HTMLInputElement).value.trim()||'16px',glow:Math.max(0,Math.min(1,Number((p.querySelector('#zx-glow')as HTMLInputElement).value)||.22)),compact:(p.querySelector('#zx-compact')as HTMLInputElement).checked,customCss:(p.querySelector('#zx-css')as HTMLTextAreaElement).value};localStorage.setItem(KEY,JSON.stringify(s));rootStyle(s);logo(s.logoUrl)});p.querySelector('#zerix-reset')?.addEventListener('click',()=>{localStorage.removeItem(KEY);rootStyle(defaults);fill()})}
icon();rootStyle(get());const start=()=>{editor();logo(get().logoUrl)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();new MutationObserver(()=>editor()).observe(document.documentElement,{childList:true,subtree:true});
