#!/usr/bin/env bash
set -Eeuo pipefail
VERSION="2.0.0"; PANEL="${ZERIX_PANEL_PATH:-/var/www/pterodactyl}"; REPO_RAW_BASE="${ZERIX_REPO_RAW_BASE:-https://raw.githubusercontent.com/alokgame2009-bot/zerix-theme/main}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; LOCAL_RESOURCES="$SCRIPT_DIR/resources"; STAMP="$(date +%Y%m%d-%H%M%S)"; BACKUP_ROOT="$PANEL/storage/zerix-theme-backup"; BACKUP="$BACKUP_ROOT/$STAMP"; INDEX="$PANEL/resources/scripts/index.tsx"; THEME_DIR="$PANEL/resources/scripts/Zerix"
RED='\033[0;31m';GREEN='\033[0;32m';YELLOW='\033[1;33m';CYAN='\033[0;36m';NC='\033[0m';say(){ printf "${CYAN}[ZERIX]${NC} %s\n" "$*"; };ok(){ printf "${GREEN}[ OK ]${NC} %s\n" "$*"; };warn(){ printf "${YELLOW}[WARN]${NC} %s\n" "$*"; };die(){ printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; exit 1; }
banner(){ clear 2>/dev/null||true; printf '\n  ╔═════════════════════════════════════════════╗\n  ║           ZERIX THEME INSTALLER            ║\n  ║        Power by SkylerNodes • Zyren         ║\n  ║                  v%s                    ║\n  ╠═════════════════════════════════════════════╣\n  ║  [1] Zerix Theme Install                    ║\n  ║  [2] Theme Uninstall                        ║\n  ║  [3] Theme Update                           ║\n  ║  [0] Exit                                   ║\n  ╚═════════════════════════════════════════════╝\n\n' "$VERSION"; }
require_root(){ [[ $EUID -eq 0 ]]||die 'Run as root.'; }; validate(){ [[ -d "$PANEL" ]]||die "Panel not found: $PANEL"; [[ -f "$INDEX" ]]||die "index.tsx not found."; command -v curl >/dev/null||die 'curl is required.'; }
load(){ if [[ -d "$LOCAL_RESOURCES/scripts/Zerix" ]];then RESOURCE_DIR="$LOCAL_RESOURCES";return;fi; TMP_DIR="$(mktemp -d)";trap 'rm -rf "${TMP_DIR:-}"' EXIT;mkdir -p "$TMP_DIR/resources/scripts/Zerix/assets";for f in main.css theme.ts assets/zerix-icon.svg assets/theme.json;do curl -fsSL "$REPO_RAW_BASE/resources/scripts/Zerix/$f" -o "$TMP_DIR/resources/scripts/Zerix/$f";done;RESOURCE_DIR="$TMP_DIR/resources"; }
backup(){ mkdir -p "$BACKUP";cp -a "$INDEX" "$BACKUP/index.tsx";[[ -d "$THEME_DIR" ]]&&cp -a "$THEME_DIR" "$BACKUP/Zerix"||true;echo "$BACKUP">"$BACKUP_ROOT/latest";say "Backup: $BACKUP"; }
imports(){ grep -Fqx "import './Zerix/main.css';" "$INDEX"||sed -i "1i import './Zerix/main.css';" "$INDEX";grep -Fqx "import './Zerix/theme.ts';" "$INDEX"||sed -i "2i import './Zerix/theme.ts';" "$INDEX"; }
remove_imports(){ sed -i "/^import ['\"]\.\/Zerix\/main\.css['\"];$/d;/^import ['\"]\.\/Zerix\/theme\.ts['\"];$/d" "$INDEX"; }
build(){ cd "$PANEL";export NODE_OPTIONS="${NODE_OPTIONS:-} --openssl-legacy-provider";if command -v yarn >/dev/null&&[[ -f yarn.lock ]];then yarn build:production;else npm run build:production;fi;php artisan optimize:clear >/dev/null 2>&1||true;chown -R www-data:www-data "$PANEL/resources/scripts/Zerix" "$PANEL/public/assets" 2>/dev/null||true; }
install(){ require_root;validate;load;backup;mkdir -p "$THEME_DIR";cp -a "$RESOURCE_DIR/scripts/Zerix/." "$THEME_DIR/";mkdir -p "$PANEL/public/assets";cp -f "$RESOURCE_DIR/scripts/Zerix/assets/zerix-icon.svg" "$PANEL/public/assets/zerix-icon.svg";cp -f "$RESOURCE_DIR/scripts/Zerix/assets/theme.json" "$PANEL/public/assets/zerix-theme.json";imports;build;ok "ZERIX $VERSION installed."; }
uninstall(){ require_root;validate;local b='';[[ -f "$BACKUP_ROOT/latest" ]]&&b="$(cat "$BACKUP_ROOT/latest")"||true;if [[ -n "$b"&&-f "$b/index.tsx" ]];then cp -a "$b/index.tsx" "$INDEX";else remove_imports;fi;rm -rf "$THEME_DIR";rm -f "$PANEL/public/assets/zerix-icon.svg" "$PANEL/public/assets/zerix-theme.json";build;ok 'ZERIX uninstalled.'; }
banner;while true;do read -r -p '  Select [0-3]: ' c;case "$c" in 1)install;;2)uninstall;;3)install;;0)exit 0;;*)warn 'Choose 0, 1, 2 or 3.';;esac;read -r -p '  Press Enter...' _;banner;done
